# ─── SonarCloud Project Configuration ───────────────────────────────────────
# Organisation and project details
sonar.organization=patilprathmesh08
sonar.projectKey=patilprathmesh08_Testing
sonar.projectName=stmTesting
sonar.projectVersion=1.0

# Source code location - only your own code
sonar.sources=Src
sonar.inclusions=**/*.c,**/*.h

# Language
sonar.language=c
sonar.c.file.suffixes=.c
sonar.h.file.suffixes=.h

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude build output and third party folders
sonar.exclusions=**/build/**,**/MCSDK_v6.4.2-Full/**,**/Drivers/CMSIS/**

# Build Wrapper output - mandatory for C/C++ accurate analysis
sonar.cfamily.build-wrapper-output=build-wrapper-output

# Quality gate - do not fail build if quality gate fails
sonar.qualitygate.wait=false

# Coverage report - add when unit tests are ready
# sonar.coverageReportPaths=coverage.info