# ─── SonarCloud Project Configuration ───────────────────────────────────────

# Organisation and project details
sonar.organization=patilprathmesh08
sonar.projectKey=patilprathmesh08_Testing
sonar.projectName=CNR-BLDC-MOTOR-FOC
sonar.projectVersion=1.0

# Source code location
sonar.sources=Src
sonar.inclusions=**/*.c,**/*.h

# Language
sonar.language=c
sonar.c.file.suffixes=.c
sonar.h.file.suffixes=.h

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude build output and third party folders
sonar.exclusions=**/build/**,**/MCSDK_v6.4.2-Full/**,**/Drivers/CMSIS/**
