# ─── SonarCloud Project Configuration ───────────────────────────────────────
# Version: v3
# Date: 24-07-2026
# File location: repo root

sonar.organization=patilprathmesh08
sonar.projectKey=patilprathmesh08_Testing
sonar.projectName=stmTesting
sonar.projectVersion=1.0

sonar.sources=CNR-Motor-Driver-1.0/Src
sonar.inclusions=**/*.c,**/*.h

sonar.language=c
sonar.c.file.suffixes=.c
sonar.h.file.suffixes=.h

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/build/**,**/MCSDK_v6.4.2-Full/**,**/Drivers/CMSIS/**,**/arm-gnu-toolchain-**/**

sonar.cfamily.compile-commands=CNR-Motor-Driver-1.0/build-wrapper-output/compile_commands.json

sonar.qualitygate.wait=false
# sonar.coverageReportPaths=coverage.info
